### ISSUE TITLE
Live demo runtime error

### ISSUE THREAD

**Issue by jaydenseric** [simonseyock/jsdoc-type-pratt-parser#21]
Exciting project, looking forward to seeing how it evolves.

The live demo seems to have a runtime error if you click the “Parse” button; I can't get it to work:

```
TypeError: undefined is not a constructor (evaluating 'new jtpp.Parser({
            mode: mode
        })')
```

<img width="731" alt="Screen Shot 2021-05-17 at 8 55 21 am" src="https://user-images.githubusercontent.com/1754873/118415471-dad79d00-b6ed-11eb-94b3-e3e5299aaa76.png">

**Comment by simonseyock** [comment]
Thanks! And thanks for reporting that! It is working again.

**Comment by simonseyock** [comment]
Yesterday I changed the main interface of the parser to a single parse function. I forgot to change that in the demo.
