### ISSUE TITLE
Create alpha release

### ISSUE THREAD

**Issue by simonseyock** [simonseyock/jsdoc-type-pratt-parser#3]
make an alpha release to npm

**Comment by simonseyock** [comment]
For this the typescript mode should basically work.

**Comment by simonseyock** [comment]
@brettz9 I think this is not yet ready for a alpha release and I think I need to put some more work in it before it really makes sense to use. But I think the pratt-parser approach makes it way easier to implement new features and also to plug together modes, compared to the pegjs approaches.

**Comment by brettz9** [comment]
> @brettz9 I think this is not yet ready for a alpha release and I think I need to put some more work in it before it really makes sense to use. But I think the pratt-parser approach makes it way easier to implement new features and also to plug together modes, compared to the pegjs approaches.

Glad to hear it! You sure appear to have come quite a long way rather quickly! With `comment-parser` having recently come to preserve all aspects including spacing for jsdoc blocks, it's heartening to hear of great promise with the type parsing as well, especially given our wish to meet people's needs with TS while being compatible with plain jsdoc as possible. Thanks for your work on this and keeping me updated!

**Comment by simonseyock** [comment]
I cerated an alpha release that is avaialble as `jsdoc-type-pratt-parser` on npm.

I am still missing some typescript functionality, for example tuples.

If you like you can also play around with the live demo: https://simonseyock.github.io/jsdoc-type-pratt-parser/

I am really interested in feedback on the results of types like this:
closure mode:
```
module:@prefix/my-module~myCallback
myObj."#weirdProp".foo
```
jsdoc mode:
```
{Array.<string>: number}
MyClass(2)
```
typescript mode:
```
(x: number, y: string, z: Class) => string
```

**Comment by brettz9** [comment]
I'm afraid my energy is rather limited, and focused with the spare energy I do have on other projects. I'd expect to be interested in seeing about adapting it for `eslint-plugin-jsdoc` if it can meet the existing features of `jsdoctypeparser`, even if the AST can't be kept the same (though the more it can, the easier the potential for migrating should be). But I'm afraid I can't contribute to the testing (or development) at such a point. But would very much look forward to the chance for it to reach such a stage.

**Comment by simonseyock** [comment]
Hey, no problem. I was just wondering if that syntax I chose is reasonable. But I might just try to improve it a little more.
